// Code generated by MockGen. DO NOT EDIT.
// Source: context-aware-error-propagator (interfaces: MetadataService)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_metadata_service.go -package=mocks . MetadataService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetadataService is a mock of MetadataService interface.
type MockMetadataService struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataServiceMockRecorder
	isgomock struct{}
}

// MockMetadataServiceMockRecorder is the mock recorder for MockMetadataService.
type MockMetadataServiceMockRecorder struct {
	mock *MockMetadataService
}

// NewMockMetadataService creates a new mock instance.
func NewMockMetadataService(ctrl *gomock.Controller) *MockMetadataService {
	mock := &MockMetadataService{ctrl: ctrl}
	mock.recorder = &MockMetadataServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataService) EXPECT() *MockMetadataServiceMockRecorder {
	return m.recorder
}

// CreateMetadata mocks base method.
func (m *MockMetadataService) CreateMetadata(filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMetadata", filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMetadata indicates an expected call of CreateMetadata.
func (mr *MockMetadataServiceMockRecorder) CreateMetadata(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMetadata", reflect.TypeOf((*MockMetadataService)(nil).CreateMetadata), filePath)
}
